export const
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',

    SAVE_CURRENT_USER = 'SAVE_CURRENT_USER',

    AUTOMOBILES_LIST_REQUEST = 'AUTOMOBILES_LIST_REQUEST',
    AUTOMOBILES_LIST_SUCCESS = 'AUTOMOBILES_LIST_SUCCESS',
    AUTOMOBILES_LIST_FAILURE = 'AUTOMOBILES_LIST_FAILURE',

    GET_AUTOMOBILE_REQUEST = 'GET_AUTOMOBILE_REQUEST',
    GET_AUTOMOBILE_SUCCESS = 'GET_AUTOMOBILE_SUCCESS',
    GET_AUTOMOBILE_FAILURE = 'GET_AUTOMOBILE_FAILURE';