export const
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',

    SAVE_CURRENT_USER = 'SAVE_CURRENT_USER',
    REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER',

    AUTOMOBILES_LIST_REQUEST = 'AUTOMOBILES_LIST_REQUEST',
    AUTOMOBILES_LIST_SUCCESS = 'AUTOMOBILES_LIST_SUCCESS',
    AUTOMOBILES_LIST_FAILURE = 'AUTOMOBILES_LIST_FAILURE',

    GET_AUTOMOBILE_REQUEST = 'GET_AUTOMOBILE_REQUEST',
    GET_AUTOMOBILE_SUCCESS = 'GET_AUTOMOBILE_SUCCESS',
    GET_AUTOMOBILE_FAILURE = 'GET_AUTOMOBILE_FAILURE',

    LOGOUT_REQUEST = 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE = 'LOGOUT_FAILURE',

    SHOW_NOTIFICATION = 'SHOW_NOTIFICATION',
    HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';